name: Build
on: [push]
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install meson ninja
    - run: sudo apt update
    - run: sudo apt install libdbus-glib-1-dev libx11-dev libgtk-3-dev libgnome-desktop-3-dev libgnomekbd-dev libpam0g-dev intltool
    - run: meson build
    - run: meson compile -C build
